### PR TITLE
Feature: List implementation

### PR DESCRIPTION
**Pull request by maxxie85**
As promised the list implementation. It's backed by the dynamic memory manager to manage a dynamic array of pointers that can grow, just as a array in .Net.

At the moment I haven't added the events that the linked list has. As far as I can see it's only used to let the enumerator know the collection has changed and the enumerator should be reset of be invalidated. I have however a different feel about it. As changing a collection while enumerating trough it is a bad idea. And doing something similar in .Net isn't even allowed and causes exceptions. 

In my case I use the enumerator as a For Each kind of thing and dispose it as soon as I'm done enumerating.

``` ST
enumerator : I_ForwardEnumerator;
list : List(4);

enumerator := list.GetEnumerator();

WHILE enumerator.MoveNext() DO
  item := enumerator.TryGet();
END_WHILE

enumerator.Dispose();
```

### CODE REVIEW

**Comment by benhar-dev** [comment]
Hi @maxxie85 this is great!

I've a few more tweaks to v0.6.0, then I'll test and prepare your PR for v0.7.0.

That raises an interesting question.  I'm keen to see this library follow best practice as much as possible, so raising exceptions on an Enumerator if the collection is modified feels like it is the correct way to go.  

The current implementation could cause bugs in the users code as the enumerator will simply return FALSE from MoveNext() which could trick the users code in to thinking that everything is ok.  There is the IsValid property, but this would only work if the user code actually uses it.

So, this raises a decision point.  Do we, 

a) create mobject-exceptions.  Add an 'InvalidOperationException' class and then raise this if you try to use an Enumerator on a modified collection. (Which feels like it is consistent with .net). Also, this gives people the ability to use Try/Catch in the future. 

b) ... not sure, happy to have other suggestions added here

z) stay as is.

It feels like we need something to tell the user code they have done something wrong as if we only write a warning in the documentation that 'you shouldn't' then that will not be read. 

Also I'd be keen to know peoples thoughts on raising exceptions is a PLC.

**Comment by benhar-dev** [comment]
Also this raises one other question about the silent fail of AddAt().  In the .net class they have Insert().  If the user code tries to insert something in the list using an index higher than the count then it raises the ArgumentOutOfRangeException.   I know we have lots of code which will silently fail rather than raise exceptions, so I wonder if there is a bigger picture we need to look in to. 

a) raise actual exceptions
b) raise our own class of exceptions
c) return true / false in the same style of Try

TwinCAT Vision uses HRESULT in a similar style so that instead of raising exceptions they pass back a hint of what failed using the HRESULT.  I originally used HRESULT on the TryGet() but this ended up complicating the code for very little extra.

**Comment by maxxie85** [comment]
Hi Ben,

Those are indeed valid questions and ultimately boils down to a design decision. In my opinion failing silently is a bad design. And true, this is not perfect yet for the List implementation. 

I don't know if exceptions is the way to go. I haven't worked with the exceptions in Beckhoff, and I don't think I will. All our objects are based around the PLCOpen model and either a triggered, or continues. Either way the have a error bit and errorID word with global errorID's describing what's wrong. This however doesn't work on the ICollection implementations. You could consider the continues model, but then they would need an enable to function and that doesn't fly with me on collections. They are to rudimentary for that. 

So I think it's better to rebuild everything to a Try{Something} and all functions return a bool indicating if the method was successful or that it failed. Then you could still introduce an errorID that will let you know what was wrong if the method failed.
I also did this with the Find on the LinkedList and rebuild it to TryFind.  

For the enumerator, this could be true as well. If you keep the link between the enumerator and the collection by the dispose and CollectionChanged event you could invalid the enumerator. And if it's invalid all the methods simply return false. This would break any loop you are in. However the programmer is still making a mistake by trying to change the collection while enumerating trough it. 

You could also change it around. And that the IEnumerable keeps track of any enumerators that are currently active. And if there is any indisposed enumerator the IEnumerable should simply refuse to allow any modifications to itself. 
The problem with this is that you need a base collection type that lives in the IEnumerable collections otherwise you would have a recurring dependency on itself and that's something the compiler doesn't catch (Causes a fun crash of the PLC on download). Or a fixed array and limiting the amount of active Enumerators. Because basically you would only need 1 at a time before disposing it. 

Another big problem I still see with the collections is type safety. As there is no direct way to ensure type safety it can cause runtime crashes if you mix them up. We could I think introduce safety checks, as the Any struct has a Type field that could be checked when adding or retrieving items from the collection. And then if the collection is empty it's open for any type. But as soon as you add your first item it lockes down to that specific type.

**Comment by piratecarrot** [comment]
I agree that collections should return a BOOL (or maybe a STRUCT of a BOOL and the error identifier) that can be checked for.
The wording "try" should then be dropped as its implied from the fact those methods can return an error.

AddItem or any other method that performs changes to the collection isn't guaranteed to succeed. Maybe you want an upper limit on a collection size or you have run out of memory. Another possibility could be a read only collection which. These would be useful to create a copy of a collection which is rapidly changing, so you can enumerate the snapshot.

Since TwinCAT PLCs are inherently multitasking, concurrent access may also warrant consideration and how a collection succeeds or fails is probably important.

Regarding type safety, genetics would be nice. I saw something that CoDeSys had generics in a new version but I haven't looked at this any further than the description.
I have a template system I was toying with in my fork of this project (features/template branch). You could create collections for all of the base types, eg List_TIME, and then use the script to generate collections for user defined types. That gives you type safety but its clunky.

**Pull request merged**
